### ISSUE TITLE
Web listener to init gyms

### ISSUE THREAD

**Issue by Flexor28** [mseleng/Kodemon#151]

**Comment by mseleng** [comment]
We must remember that his is needed not only in the `spring-mvc` module, but also in the `rest` module

**Comment by mseleng** [comment]
@Flexor28 I think that we can probably skip this for now, as we have sample-data in the project, which takes care of initializing

**Comment by Flexor28** [comment]
Yeah I agree with you. I think that sample-data are already doing this job, so maybe we can close this one?

**Comment by mseleng** [comment]
Not sure, whether close, because as the name suggests, this data is sample, so kinda "for testing purposes only" so If we want to put the application to the production (when Nintendo buy this project) we will have ti implement that listener maybe we should just set the label to wontfix and delete milestone from this. Do you agree?

**Comment by marosseleng** [comment]
Closing with wontfix
