### ISSUE TITLE
Create admin role in system

### ISSUE THREAD

**Issue by Flexor28** [mseleng/Kodemon#163]
Administrator should also have some extra capabilities and it should be implemented in user interface.

**Comment by mseleng** [comment]
@Flexor28 Do we really need an admin role? Because if you look in our use-case diagram, there are two roles specified as "User" and "Visitor" I think, wo I think we should keep up with this and implement roles like that. And according to the assignment, roles should be distinguishable by the amount of operations they can perform, so this should be easy in this case, as the Visitor can basically do any "read" operation, whereas the User can perform also "write" operations. What do you think? Others? @matejos @Ahimtar

**Comment by matejos** [comment]
Well in reality, there really should be an ability of somebody having "delete" permissions (and we don't want to give this to regular users), but I don't know if it's necessary for this project...

**Comment by mseleng** [comment]
Yes, but I am not sure whether we are capable to implement this till the deadline :smile: Yes, we should implement it maybe to the final project, but now I think it is easier to look at two roles as visitor/user, but It is open for discussion.

**Comment by matejos** [comment]
Alright, if we want, we can implement it sometime between milestone3 and final version (72 hours before defense)

**Comment by mseleng** [comment]
Yep, there is already final milestone on GH, but let's leave this issue in M3 for now abd we will see

**Comment by Flexor28** [comment]
I will try to implement this till M3 if there wont be nothing more important to do. But if I won't do it on time, I think that visitor and trainer could be enough to have different roles in system.

**Comment by mseleng** [comment]
Okay, great!

**Comment by mseleng** [comment]
@Flexor28 close pls. #167 also
